MODEL:
  TYPE: 'evopose'
  GENOTYPE: [
    [ 3, 3, 2, 1 ],
    [ 3, 3, 3, 2 ],
    [ 5, 4, 5, 2 ],
    [ 3, 3, 9, 2 ],
    [ 5, 3, 14, 1 ],
    [ 5, 4, 18, 1 ],
    [ 3, 2, 7, 1 ]
  ]
  LOAD_WEIGHTS: false

TRAIN:
  BATCH_SIZE: 128
  EPOCHS: 200
  WARMUP_EPOCHS: 5
  LR_SCHEDULE: 'warmup_cosine_decay'
  SAVE_META: true

VAL:
  BATCH_SIZE: 128
  DROP_REMAINDER: true
  DET: true
  SAVE_BEST: true

DATASET:
  INPUT_SHAPE: [512, 384, 3]
  TFRECORDS: 'gs://willmcnally1/TF2-SimpleHumanPose/tfrecords'
  ANNOT: '/home/willmcnally1/coco/annotations/person_keypoints_val2017.json'
  CACHE: true
  BFLOAT16: true


