MODEL:
  TYPE: 'evopose'

SEARCH:
  CHILDREN: 32
  PARENTS: 4
  GEN0_EPOCHS: 1
  EPOCHS: 5
  TARGET: 5000000  # parameters
  W: -0.04

TRAIN:
  BATCH_SIZE: 1024
  DISP: false
  LR_SCHEDULE: 'constant'
  BASE_LR: 0.001
  SCALE_LR: false

VAL:
  BATCH_SIZE: 256
  FLIP: true
  DET: false
  DROP_REMAINDER: true

DATASET:
  TFRECORDS: 'gs://willmcnally1/TF2-SimpleHumanPose/tfrecords'
  ANNOT: '/home/willmcnally1/coco/annotations/person_keypoints_val2017.json'
  ROT_PROB: 0.
  SCALE_FACTOR: 0.
  BFLOAT16: true
  CACHE: true

