MODEL:
  TYPE: 'simple_baseline'
  BACKBONE: 'resnet50'
  HEAD_CHANNELS: 256
  HEAD_KERNEL: 4
  HEAD_ACTIVATION: 'relu'

TRAIN:
  BATCH_SIZE: 1024
  EPOCHS: 200
  WARMUP_EPOCHS: 5
  LR_SCHEDULE: 'warmup_cosine_decay'

VAL:
  BATCH_SIZE: 256
  DROP_REMAINDER: True
  DET: True

DATASET:
  TFRECORDS: 'gs://willmcnally1/TF2-SimpleHumanPose/tfrecords'
  ANNOT: '/home/willmcnally1/coco/annotations/person_keypoints_val2017.json'
  CACHE: true
  BFLOAT16: true


