MODEL:
  NAME: 'sb_resnet50_256x192_tpu'
  TYPE: 'simple_baseline'
  BACKBONE: 'resnet50'
  HEAD_CHANNELS: 256
  HEAD_KERNEL: 4
  HEAD_ACTIVATION: 'relu'

TRAIN:
  BATCH_SIZE: 256
  EPOCHS: 140
  WARMUP_EPOCHS: 5
  LR_SCHEDULE: 'warmup_piecewise'
  DECAY_EPOCHS: [90, 120]

VAL:
  BATCH_SIZE: 256
  DROP_REMAINDER: True
  DET: True

DATASET:
  TFRECORDS: 'gs://willmcnally1/TF2-SimpleHumanPose/tfrecords'
  ANNOT: '/home/willmcnally1/coco/annotations/person_keypoints_val2017.json'
  CACHE: true
  BFLOAT16: true


